Revert "Bump org.jetbrains.skiko:skiko-awt from 0.9.39 to 0.9.40"
This reverts commit 2ee20f05dbd733b4a439d84f57cb33e5e5a495f4.

its is broken on macos arm with:

Error was captured in composition.
java.lang.UnsatisfiedLinkError: 'int org.jetbrains.skiko.MetalApiKt.getAdapterMaxTextureSize(long)'
	at org.jetbrains.skiko.MetalApiKt.getAdapterMaxTextureSize(Native Method)
	at org.jetbrains.skiko.MetalApiKt.chooseMetalAdapter(MetalApi.kt:18)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.<init>(MetalRedrawer.kt:62)
	at org.jetbrains.skiko.Actuals_awtKt$makeDefaultRenderFactory$1.createRedrawer(Actuals.awt.kt:22)
	at org.jetbrains.skiko.SkiaLayer.redrawerManager$lambda$7(SkiaLayer.awt.kt:345)
	at org.jetbrains.skiko.redrawer.RedrawerManager.findNextWorkingRenderApi(RedrawerManager.kt:33)
	at org.jetbrains.skiko.SkiaLayer.init(SkiaLayer.awt.kt:373)
	at org.jetbrains.skiko.SkiaLayer.addNotify(SkiaLayer.awt.kt:259)
	at androidx.compose.ui.scene.skia.WindowSkiaLayerComponent$contentComponent$1.addNotify(WindowSkiaLayerComponent.desktop.kt:84)